AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A starter AWS Lambda function.
Resources:
  # Criar função lambda agendada
  lambdafunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: dataops-coleta-vacinas-ci-cd # nome da função
      Handler: lambda_function.lambda_handler # nome do arquivo e método de onde está a função
      Runtime: python3.7 # ambiente de execução
      CodeUri: ./app # local onde estarão os arquivos da função
      Description: Coletar dados de vacinas.
      MemorySize: 512 # memória utilizada pela funçãop
      Timeout: 900 # tempo máximo de execução, em segundos
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/LabRole # IAM role da função para permissões a outros recursos da AWS
      Events: # Evento agendado para execução
        ScheduledFunction:
          Type: Schedule
          Properties:
            Schedule: cron(15 00 * * ? *) # executa todo dia às 10:15
            Name: dataops-agenda-coleta-vacina
            Input: '{
              "url":"https://dados-vacinas-fsousa.s3.amazonaws.com/part-00000-ac297e25-1037-4cbd-9bc8-222e8f43bfe0.c000.csv", 
              "uf":"ac"
            }' # evento com parâmetros que serão enviados para a função lambda
